# Generated by Django 2.2.2 on 2020-06-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20200624_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read full story', max_length=300),
        ),
    ]
